### ISSUE TITLE
Individual messaging issue

### ISSUE THREAD

**Issue by janesth** [janesth/team_bot#12]
Issue found in #2: 

`Guild.loadMembers()` fails due to an exception.

Leads:
- GatewayIntent

**Comment by Aatha-Sivas** [comment]
TODO: 

- Upon receiving lobby invite URL, send URL to Teammate and Opponents 
- Send URL to GLOBAL_CHANNEL for spectators with the Match Up. Example:

`[YOINC_acc01 & YOINC_acc09]  VS  [YOINC_acc03 & YOINC_acc05] starting now: `
`Spectators may join the Room using <URL>`
`GLHF 30!`

**Comment by Aatha-Sivas** [comment]
Implementation of "Role Host" in a62d5bd wrong. Issue: 

-  Instead of sending notification to every "Team Leader", it should only send a notification to one player of each Match Up

Blocked due to #11

**Comment by janesth** [comment]
Resolved in ``feature/issue-12``.
