### ISSUE TITLE
Match Result Logic

### ISSUE THREAD

**Issue by janesth** [janesth/team_bot#17]
TBD

**Comment by Aatha-Sivas** [comment]
Logic implemented in edf9ace:

- After a match, the assigned host sends the Bot the match result from their perspective, meaning if their opponent won and they lost the match,  they need to send the match results to the bot using `/result lost`. (Regex: `/result <won/lost>`)

- The winners and losers of each match are stored in their respective List `winnerPlayers` and `loserPlayers`. This enables us to print out this of Players who dropped out and the ones who advance to next round, after all matches have been finished.

- When all Matches have been finished, the admin can run the `/start` command again to start a new round. During the command, all players in `loserPlayers` will be deleted from the map `claimedAccounts`. Recovery File of `claimedAccounts` to be implemented in #14.

- In the special case where the host of a match has mistakenly entered the wrong match result, they can contact the admin using `/say` (to be implemented in #18). The admin can use the command `/correctresult <Host ID> <won/lost>`, where the Host ID is the number of the host's account (e.g. yoinc_0**9** or yoinc _**10**) is. With this they can change the result of the match. The deletion of the players from `claimedAccounts` will only be executed when the command `/start` is executed. Until then, all match results of the current round can be changed with no issues.

**Comment by janesth** [comment]
Resolved and merged.
