### ISSUE TITLE
Say command for communicating anonymously

### ISSUE THREAD

**Issue by Aatha-Sivas** [janesth/team_bot#18]
- By using the command `/say <String>`, a user can directly communicate with another user while remaining anonymous.

- The command can be overloaded by adding a simple `/say <String>` and `/say <AccountID> <String>` command, where the AccountID is the number of the recipient's account (e.g. yoinc_09 or yoinc _10).

- A message from the bot could be formatted like the following:

>  [CHAT] - `yoinc_09` says: "Hello Friend, 79"

-  If a problem occurs in a match up, the user could use `/say admin <String>` to contact the admin.

-  Beware, if the admin is also a participant, they should have the option to reply to a user as an admin (e.g `admin says...`) or reply with their normal AccountID, i.e. more overloading of the command `/say asAdmin <String>`, which is only applicable to admins.

**Comment by janesth** [comment]
Resolved and merged.
